// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package hello_service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Req
	Resp
*/
package hello_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req_GenderType int32

const (
	Req_UNKNOWN Req_GenderType = 0
	Req_MALE    Req_GenderType = 1
	Req_FEMALE  Req_GenderType = 2
)

var Req_GenderType_name = map[int32]string{
	0: "UNKNOWN",
	1: "MALE",
	2: "FEMALE",
}
var Req_GenderType_value = map[string]int32{
	"UNKNOWN": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x Req_GenderType) String() string {
	return proto.EnumName(Req_GenderType_name, int32(x))
}
func (Req_GenderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Req struct {
	Id     int32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age    int32          `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Gender Req_GenderType `protobuf:"varint,4,opt,name=gender,enum=hello.service.Req_GenderType" json:"gender,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Req) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Req) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Req) GetGender() Req_GenderType {
	if m != nil {
		return m.Gender
	}
	return Req_UNKNOWN
}

type Resp struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Req)(nil), "hello.service.Req")
	proto.RegisterType((*Resp)(nil), "hello.service.Resp")
	proto.RegisterEnum("hello.service.Req_GenderType", Req_GenderType_name, Req_GenderType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	Hello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Hello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := grpc.Invoke(ctx, "/hello.service.Hello/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	Hello(context.Context, *Req) (*Resp, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.service.Hello/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Hello(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.service.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Hello_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x97, 0xb6, 0xab, 0xee, 0x93, 0x8d, 0xee, 0xf3, 0x12, 0x04, 0xa1, 0xf4, 0x94, 0x53,
	0x84, 0x8a, 0x27, 0x4f, 0x0e, 0xa6, 0x82, 0x5a, 0x47, 0x54, 0x3c, 0x6f, 0xeb, 0x47, 0x2d, 0xac,
	0x4b, 0xd6, 0x88, 0xe0, 0xfe, 0x1d, 0xff, 0x51, 0x49, 0xdc, 0x90, 0xd1, 0xdb, 0x2f, 0x2f, 0x8f,
	0xf7, 0x3d, 0x1e, 0x0c, 0x2d, 0xb5, 0x5f, 0xf5, 0x92, 0xa4, 0x69, 0xf5, 0xa7, 0xc6, 0xe1, 0x07,
	0xad, 0x56, 0x5a, 0xee, 0xc4, 0xec, 0x87, 0x41, 0xa8, 0x68, 0x83, 0x23, 0x08, 0xea, 0x92, 0xb3,
	0x94, 0x89, 0xbe, 0x0a, 0xea, 0x12, 0x11, 0xa2, 0xf5, 0xbc, 0x21, 0x1e, 0xa4, 0x4c, 0x0c, 0x94,
	0x67, 0x4c, 0x20, 0x9c, 0x57, 0xc4, 0x43, 0x6f, 0x72, 0x88, 0x57, 0x10, 0x57, 0xb4, 0x2e, 0xa9,
	0xe5, 0x51, 0xca, 0xc4, 0x28, 0x3f, 0x97, 0x07, 0xe9, 0x52, 0xd1, 0x46, 0xde, 0x79, 0xc3, 0xeb,
	0xb7, 0x21, 0xb5, 0x33, 0x67, 0x17, 0x00, 0xff, 0x2a, 0x9e, 0xc0, 0xd1, 0x5b, 0xf1, 0x50, 0x3c,
	0xbf, 0x17, 0x49, 0x0f, 0x8f, 0x21, 0x7a, 0xba, 0x79, 0x9c, 0x26, 0x0c, 0x01, 0xe2, 0xdb, 0xa9,
	0xe7, 0x20, 0xe3, 0x10, 0x29, 0xb2, 0xc6, 0x35, 0x68, 0x6c, 0xe5, 0x6b, 0x0e, 0x94, 0xc3, 0xfc,
	0x1a, 0xfa, 0xf7, 0xee, 0x24, 0xe6, 0x7b, 0xc0, 0x6e, 0x87, 0xb3, 0xd3, 0x8e, 0x66, 0x4d, 0xd6,
	0x9b, 0x08, 0x18, 0x2f, 0x75, 0x23, 0xb7, 0x5b, 0x69, 0x16, 0xfb, 0xbf, 0xc9, 0xd8, 0xc7, 0xbc,
	0xfc, 0xbd, 0x66, 0x6e, 0xb3, 0x19, 0x5b, 0xc4, 0x7e, 0xbc, 0xcb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x62, 0x5f, 0x32, 0x4b, 0x4d, 0x01, 0x00, 0x00,
}
